### ISSUE TITLE
Few documentation to get started

### ISSUE THREAD

**Issue by JohnBerd** [aileo/oiler#1]
Hello, thank you for providing us this great project.

Could it be possible to get a "getting started" section in the README.md with a little example?

**Comment by aileo** [comment]
Good point, this project is in very early stage so I did not get into the documentation for now and I admit I do not know where to start from.
In the current state, you can find a complete example in the `dev` folder.

**Comment by aileo** [comment]
I think we could use this issue to start a discussion about what we want to see in the "getting started" and in what order.

Some bullet points to start :

- Set common components (Header, footer, modal wrapper, ...)
- Register service
- Register action
- Register Page/Modal
  - routing
  - bindings

**Comment by JohnBerd** [comment]
Ok so `npm run dev` launches the example.

Those bullet points would give a great overview of the project.

**Comment by aileo** [comment]
closed with #2
