### ISSUE TITLE
Possibility to handle a JWT

### ISSUE THREAD

**Issue by JohnBerd** [aileo/oiler#6]
Hello and thank you again for your work on this project,

Most of my apps use a javascript web token injected in the header requests to authenticate the user.

Here is how the user flow is working:

- The app checks if there is a JWT in the local storage before the app renders
- if it is not found, the app renders and the user stays as not authenticated in the global state
- if it is found:
  - the token is globally injected in the header (not the right way to do in some applications using several APIs)
  - A first API call is done to check if it can grab the user:
    - if it is the case, the JWT is stored in the local storage and the user is marked as authenticated in the global state, the app renders
    - if the request returns an error, the token is removed from request headers and the local storage. The app renders.

Concerning the logout, the token is removed from the global state, the local storage and from the request headers.

In your opinion, what part of this can be handled by Oiler and what is up to the developper?
What can be developped in Oiler to help going on with this flow?

**Comment by aileo** [comment]
I think it can be split in several features:
- some LocalStorage and state sync mecanism
- actions on start (it can be done already by listening start event: `oiler.on('start', () => { ... })`)
- something that can inject state part in fetchery requests (headers, body, query...)

`oiler.login()` method could also take some data as a parameter to store in the state (the JWT in your case).

The workflow would then be something like:
- set path of the state to sync with LocalStorage (so it will get the JWT if any)
- add services (Fetchery) with the state injection (so it add the JWT in the headers if any)
- add actions that use the services to get the user from the API and process result (call login or not)
- call this action on start

I think the state injection in requests belong the Fetchery repo.

What do you think ?

**Comment by JohnBerd** [comment]
It seems to exactly suit my needs, this workflow is perfect for a JWT strategy and responsibilities are well dealt between Fetchery and Oiler to keep using Oiler with different strategies.

Thank you!

**Comment by aileo** [comment]
I just updated Fetchery for this usecase, you could have something like this:

```js

import app from 'oiler';

// Add API client
app.addClient(
  'api',
  'http://127.0.0.1:8080',
  {
    headers: {
      Authorization() {
        // Get token from state
        const token = app.state.get(['user', 'JWT']);
        if (!token) return undefined; // do not set header if no token
        return `Bearer ${token}`;
      }
    },
    contentType: CONTENT_TYPE.JSON,
  },
  {
    'user.get': { route: '/api/user' },
  }
);

const JWT = app.state.select(['user', 'JWT']);
// Add state to local storage mechanism
JWT.on('update', ({ data }) => {
  localStorage.setItem('JWT', data.currentData);
});
// Init state from local storage
JWT.set(localStorage.getItem('JWT'));
```
I don't think the state/localStorage sync mechanism belongs to this lib as it is very light to setup this way.
